# Generated by Django 4.1 on 2022-08-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Completion',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='room',
        ),
    ]
