# Generated by Django 4.1 on 2022-08-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_completion_status_rename_status_status_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
    ]
